import {test} from 'node:test';
import assert from 'node:assert/strict';
import {validateSpec,validateAnswers,gate,loopbackEndpoint,illustrative,trialMetrics,requestFor,decide,generate} from '../site/decision-models/core.js';
import {examples} from '../site/decision-models/examples.js';
for(const [name,s] of Object.entries(examples))test(`schema and synthetic roundtrip: ${name}`,()=>{assert.deepEqual(validateSpec(s),s);validateAnswers(illustrative(s).data,s.questions);});
test('generated executable fields and prototype IDs are refused',()=>{assert.throws(()=>validateSpec({...examples.tools,script:'alert(1)'}));assert.throws(()=>validateSpec({...examples.tools,questions:JSON.parse('{"__proto__":{"type":"noul","instructions":"test"}}')}));});
test('shape, null, empty instructions and out-of-contract levels rejected',()=>{for(const s of [null,{}, {...examples.tools,state:''},{...examples.tools,questions:{a:{type:'chat',instructions:'text'}}},{...examples.score,questions:{a:{type:'score',instructions:'x',criteria:['a']}}}])assert.throws(()=>validateSpec(s));});
test('Noul has two-sided abstention, Choice gates on confidence not pmax',()=>{assert.equal(gate({type:'noul',noul:.05},.8),'negative');assert.equal(gate({type:'noul',noul:.5},.8),'review');assert.equal(gate({type:'noul',noul:.8},.8),'positive');assert.equal(gate({type:'choice',confidence:.7},.8),'review');assert.throws(()=>gate({},NaN));});
test('loopback boundary refuses remote hosts, redirects-in-query and URL credentials',()=>{assert.equal(loopbackEndpoint('http://127.0.0.1:8009/v1/systemone'),'http://127.0.0.1:8009/v1/systemone');for(const v of ['https://evil.test/v1/systemone','http://localhost.evil.test/v1/systemone','http://user:secret@localhost/v1/systemone','javascript:alert(1)','http://localhost/v1/systemone?to=https://evil.test','http://localhost/other'])assert.throws(()=>loopbackEndpoint(v));});
test('response is fail-closed for missing answers, unknown options, non-finite and bad distributions',()=>{const s=examples.tools,d=illustrative(s).data;for(const mutate of [d=>delete d.answers.action,d=>d.answers.action.choice='run_shell',d=>d.answers.action.confidence=NaN,d=>d.answers.action.probabilities.list_tabs=9,d=>d.answers.action.probabilities={list_tabs:1}]){const c=structuredClone(d);mutate(c);assert.throws(()=>validateAnswers(c,s.questions));}});
test('multiclass Brier formula and expected label validation',()=>{const a={type:'choice',choice:'a',confidence:.8,probabilities:{a:.8,b:.2}};const m=trialMetrics(a,'b',.9);assert.equal(m.correct,false);assert.ok(Math.abs(m.brier-1.28)<1e-10);assert.equal(m.gate,'review');assert.throws(()=>trialMetrics(a,'c',.8));});
test('illustration ignores text and discloses synthetic provenance',()=>{const a=illustrative(examples.tools),b=illustrative({...examples.tools,state:'Anything entirely different'});assert.deepEqual(a,b);assert.match(a.source,/ILLUSTRATIVE/);assert.match(a.data.model,/not-a-model/);});
test('request excludes keys and generator fields',()=>{const r=requestFor(examples.tools,'jev-1.13.0');assert.deepEqual(Object.keys(r),['model','state','questions']);});
test('real decision adapters use correct host, key boundary and validation (mock transport)',async()=>{
 const original=globalThis.fetch,calls=[];globalThis.fetch=async(url,options)=>{calls.push({url,options});return {ok:true,json:async()=>illustrative(examples.tools).data};};
 try{await decide(examples.tools,{provider:'jev',key:'synthetic-test-only',model:'jev-1.13.0'});await decide(examples.tools,{provider:'kev',key:'must-not-send',endpoint:'http://localhost:8009/v1/systemone',model:'kev-latest'});assert.equal(calls[0].url,'https://api.typesafe.ai/v1/systemone');assert.equal(calls[0].options.headers.Authorization,'Bearer synthetic-test-only');assert.equal(calls[1].options.headers.Authorization,undefined);assert.equal(calls[0].options.redirect,'error');assert.equal(calls[0].options.credentials,'omit');}finally{globalThis.fetch=original;}
});
test('OpenAI and Claude generation validate JSON and reject code (mock transport)',async()=>{const original=globalThis.fetch,calls=[];globalThis.fetch=async(url,options)=>{calls.push({url,options});return {ok:true,json:async()=>url.includes('anthropic')?{content:[{type:'text',text:JSON.stringify(examples.tools)}]}:{choices:[{message:{content:JSON.stringify(examples.tools)}}]}};};try{for(const provider of ['openai','claude'])assert.deepEqual(await generate('test',{provider,key:'synthetic-test-only',model:'test'}),examples.tools);assert.equal(calls[1].options.headers['anthropic-dangerous-direct-browser-access'],'true');globalThis.fetch=async()=>({ok:true,json:async()=>({choices:[{message:{content:'<script>alert(1)</script>'}}]})});await assert.rejects(()=>generate('test',{provider:'openai',key:'synthetic',model:'test'}),/valid JSON/);}finally{globalThis.fetch=original;}});
